
spring.datasource.url=jdbc:mysql://mysql-container:3306/MotorcycleDB
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.motorcycle.domain
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.org.mybatis.SQL=INFO
logging.level.com.example.motorcycle=INFO

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# ?? ??? ??
spring.servlet.multipart.location=/app/temp
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ?? ??? ??
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**
images.path=/app/src/main/resources/static/images
image.upload.directory=/app/src/main/resources/static/images
image.temp.directory=/app/src/main/resources/static/images/temp
image.trashcan.directory=/app/src/main/resources/static/images/TrashCan


server.address=0.0.0.0
server.port=8080


server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
security.headers.content-security-policy=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'
server.servlet.session.tracking-modes=cookie
server.servlet.session.timeout=30m

mybatis.config-location=classpath:mybatis-config.xml

# Email Configuration for Kakao
spring.mail.host=smtp.kakao.com
spring.mail.port=465
spring.mail.username=ryan03255
spring.mail.password=cabhckpeswjotmbo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.kakao.com

# Additional Kakao Mail Properties
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.debug=true

