#name: Docker Build and Push
#
#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Java 설정
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'gradle'
#
#      - name: Gradle 권한 설정
#        run: chmod +x gradlew
#
#      - name: Gradle 빌드
#        run: ./gradlew build -x test
#
#      - name: Docker 로그인
#        uses: docker/login-action@v2
#        with:
#          username: 88motorcycle
#          password: ${{ secrets.DOCKER_TOKEN }}
#
#      - name: Build and Push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: |
#            88motorcycle/motorcycle:latest
#            88motorcycle/motorcycle:${{ github.sha }}
#          cache-from: type=registry,ref=88motorcycle/motorcyclepick:latest
#          cache-to: type=inline

name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Java 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle 권한 설정
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew build -x test

      - name: Pull buildkit image
        run: docker pull moby/buildkit:buildx-stable-1

      - name: Docker 로그인
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: 88motorcycle
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --debug
          driver: docker-container

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/88motorcycle/motorcycle:latest
            docker.io/88motorcycle/motorcycle:${{ github.sha }}
          cache-from: |
            type=registry,ref=docker.io/88motorcycle/motorcycle:buildcache
          cache-to: |
            type=registry,ref=docker.io/88motorcycle/motorcycle:buildcache,mode=max